name: CI/CD

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
      - 'CHANGELOG.md'
      - 'MAINTAINERS.md'
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: supabase/actions/.github/workflows/python-ci.yml@guilherme/python-ci
    with:
      enable-publish: true
      package-name: 'supabase'
    secrets:
      COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
